config/routes.rb
Connectedin::Application.routes.draw do
  root "students#show_all", as: 'home'
  get "/students/show_harsh" => "students#show_harsh", as: 'harsh'
  get "/harsh" => "students#show_harsh"
  get "/students/show_nicole" => "students#show_nicole", as: 'nicole'
  get "/nicole" => "students#show_nicole"
  get "/students/show_yasmin" => "students#show_yasmin", as: 'yasmin'
  get "/yasmin" => "students#show_yasmin"
  get "/404" => "error_pages#404", as: 'four_oh_four'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  unless Rails.application.config.consider_all_requests_local
    rescue_from ActiveRecord::RecordNotFound,
                ActionController::RoutingError,
                ActionController::UnknownController,
                ActionController::UnknownAction,
                ActionController::MethodNotAllowed do |exception|

      redirect_to four_oh_four_path
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show_all
    @all = [show_harsh, show_nicole, show_yasmin]
  end

  def show_harsh
    @student = {
        name: "Harsh Patel",
        city: "St. Louis",
        description: "The Indian man with glasses",
        picture_url: "http://goo.gl/GwwMqe",
        path: harsh_path
    }
  end

  def show_nicole
    @student = {
        name: "Nicole Pank",
        city: "Jersey Shore",
        description: "Actually North Jersey",
        picture_url: "https://scontent-b-dfw.xx.fbcdn.net/hphotos-ash3/1174903_828444650107_128913837_n.jpg",
        path: nicole_path
    }
  end

  def show_yasmin
    @student = {
        name: "Yasmin Fazelinia",
        city: "Austin",
        description: "I dont know....",
        picture_url: "https://scontent-b-dfw.xx.fbcdn.net/hphotos-frc3/1904_10102889709685500_129841736_n.jpg",
        path: yasmin_path
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connectedin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/show_all.html.erb
<%= link_to "home", home_path %>
<h1>ConnectedIn</h1>
<h3>Come and meet some people... and stuff</h3>
<% @all.each do |person| %>
  <%= person[:name] %>
  <br />
  <%= person[:city] %>
  <br />
  <%= person[:description] %>
  <br />

  <%= link_to image_tag(person[:picture_url], :width => 200), person[:path] %>

  <br />
  <br />
<% end %>

app/views/students/show_harsh.html.erb
<%= link_to "home", home_path %> > <%= link_to "harsh", harsh_path %>
<h1>ConnectedIn</h1>
<h3>Come and meet some people... and stuff</h3>
<%= link_to image_tag(@student[:picture_url], :width => 200), home_path %>
<br />
<br />
<%= @student[:name] %>
<br />
<%= @student[:description] %>
<br />
<%= @student[:city] %>
<br />
<%= @student[:path] %>

app/views/students/show_nicole.html.erb
<%= link_to "home", home_path %> > <%= link_to "nicole", nicole_path %>
<h1>ConnectedIn</h1>
<h3>Come and meet some people... and stuff</h3>
<%= link_to image_tag(@student[:picture_url], :width => 200), home_path %>
<br />
<br />
<%= @student[:name] %>
<br />
<%= @student[:description] %>
<br />
<%= @student[:city] %>
<br />
<%= @student[:path] %>

app/views/students/show_yasmin.html.erb
<%= link_to "home", home_path %> > <%= link_to "yasmin", yasmin_path %>
<h1>ConnectedIn</h1>
<h3>Come and meet some people... and stuff</h3>
<%= link_to image_tag(@student[:picture_url], :width => 200), home_path %>
<br />
<br />
<%= @student[:name] %>
<br />
<%= @student[:description] %>
<br />
<%= @student[:city] %>
<br />
<%= @student[:path] %>